name: compile
on:
  push:
    branches: 
      - ci
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout
      run: curl -O -L https://raw.githubusercontent.com/zhaofeng-shu33/slurm-test-env/master/build.sh
    - name: run script
      run: bash build.sh

